// Vocabulaire affiché : tout terme technique a son équivalent en français courant.
// Les clés techniques (CREATE_DEAL, OBSERVED…) restent visibles en info-bulle et dans la vue détaillée.

export const VERB_FR: Record<string, string> = {
  SEARCH: "Rechercher",
  RECOMMEND: "Recommander",
  COMPARE: "Comparer",
  READ: "Consulter",
  LIST: "Lister",
  EXPORT: "Exporter",
  MONITOR: "Suivre",
  CREATE: "Créer",
  UPDATE: "Modifier",
  DELETE: "Supprimer",
  SUBMIT: "Soumettre",
  SEND: "Envoyer",
  CALL: "Appeler",
  CHECK_PRICE: "Vérifier un prix",
  CHECK_AVAILABILITY: "Vérifier une disponibilité",
  ADD_TO_CART: "Ajouter au panier",
  CHECKOUT: "Commander",
  PAY: "Payer",
  REFUND: "Rembourser",
  BOOK: "Réserver",
  MODIFY: "Modifier une réservation",
  CANCEL: "Annuler",
};

export const OBJECT_FR: Record<string, string> = {
  CONTACT: "Contacts",
  COMPANY: "Entreprises",
  DEAL: "Opportunités",
  PIPELINE: "Pipelines de vente",
  TASK: "Tâches",
  NOTE: "Notes",
  EMAIL: "Emails",
  MEETING: "Rendez-vous",
  QUOTE: "Devis",
  INVOICE: "Factures",
  PRODUCT: "Produits",
  TICKET: "Tickets",
  REPORT: "Rapports",
  SMS: "SMS",
  MESSAGE: "Conversations",
  RECORD: "Fiches (tous types)",
  USER: "Utilisateurs",
  CART: "Paniers",
  ORDER: "Commandes",
  CUSTOMER: "Clients",
  PAYMENT: "Paiements",
  REFUND: "Remboursements",
  SHIPMENT: "Livraisons",
  INVENTORY: "Stocks",
  DISCOUNT: "Promotions",
  RETURN: "Retours",
  REVIEW: "Avis",
  PRICE: "Prix",
  PROPERTY: "Hébergements",
  ROOM: "Chambres",
  FLIGHT: "Vols",
  AVAILABILITY: "Disponibilités",
  BOOKING: "Réservations",
  GUEST: "Voyageurs",
  BILL: "Factures fournisseurs",
  EXPENSE: "Dépenses",
  TRANSACTION: "Transactions",
  ACCOUNT: "Comptes",
  SUPPLIER: "Fournisseurs",
  TAX: "Taxes",
  DOCUMENT: "Documents",
  EVENT: "Événements",
  PROJECT: "Projets",
  BOARD: "Tableaux",
  // marchés de contrôle : e-commerce, compta, gestion de projet, paiement, création
  STORE: "Boutiques",
  CREDIT: "Avoirs",
  ITEM: "Articles",
  EMPLOYEE: "Salariés et paie",
  ISSUE: "Tickets",
  COMMENT: "Commentaires",
  DATABASE: "Bases de données",
  SPRINT: "Sprints",
  TEAM: "Équipes et espaces",
  PORTFOLIO: "Portefeuilles de projets",
  TIME: "Temps passé",
  FILE: "Fichiers",
  SUBSCRIPTION: "Abonnements",
  PAYOUT: "Virements sortants",
  DISPUTE: "Litiges",
  LINK: "Liens de paiement",
  MANDATE: "Mandats de prélèvement",
  BALANCE: "Solde",
  TERMINAL: "Terminaux de paiement",
  DESIGN: "Designs",
  VIDEO: "Vidéos",
  IMAGE: "Images",
  AUDIO: "Audio",
  ASSET: "Médias",
  CAPTION: "Sous-titres",
  BRAND: "Charte graphique",
  JOB: "Rendus en cours",
  // sujets proposés par l'IA pour les marchés créés en masse (vocabulaires « online bank », « food delivery »…)
  ACTION: "Actions",
  ACTIVITY: "Activités",
  ADDRESS: "Adresses",
  AGENT: "Agents",
  ALERT: "Alertes",
  APP: "Applications",
  APPLICATION: "Candidatures",
  APPOINTMENT: "Rendez-vous",
  APPROVAL: "Validations",
  ARTICLE: "Articles",
  ASSESSMENT: "Évaluations",
  ASSIGNMENT: "Devoirs",
  ATTACHMENT: "Pièces jointes",
  ATTENDEE: "Participants",
  AUDIT: "Audits",
  AUTOMATION: "Automatisations",
  BACKUP: "Sauvegardes",
  BENEFICIARY: "Bénéficiaires",
  BENEFIT: "Avantages salariés",
  BUDGET: "Budgets",
  BUILD: "Builds",
  CALENDAR: "Agendas",
  CAMPAIGN: "Campagnes",
  CANDIDATE: "Candidats",
  CARD: "Cartes",
  CARRIER: "Transporteurs",
  CATEGORY: "Catégories",
  CERTIFICATE: "Certificats",
  CHAT: "Discussions",
  CHECKIN: "Enregistrements",
  CLAIM: "Sinistres",
  CLASS: "Cours",
  CLAUSE: "Clauses",
  CLIENT: "Clients",
  CLUSTER: "Clusters",
  COHORT: "Cohortes",
  CONNECTION: "Connexions",
  CONSULTATION: "Consultations",
  CONTRACT: "Contrats",
  CONVERSATION: "Conversations",
  COURIER: "Livreurs",
  COURSE: "Formations",
  COVERAGE: "Garanties",
  CREDENTIAL: "Identifiants",
  CUSTOMS: "Douanes",
  DASHBOARD: "Tableaux de bord",
  DELIVERY: "Livraisons",
  DEPARTMENT: "Services",
  DEPLOYMENT: "Déploiements",
  DEPOSIT: "Dépôts",
  DEVICE: "Appareils",
  DISCUSSION: "Discussions",
  DISH: "Plats",
  DIVIDEND: "Dividendes",
  DOMAIN: "Domaines",
  DRIVE: "Disques",
  DRIVER: "Chauffeurs",
  ENDORSEMENT: "Avenants",
  ENROLLMENT: "Inscriptions",
  ENVELOPE: "Enveloppes",
  ENVIRONMENT: "Environnements",
  ERROR: "Erreurs",
  EXPERIMENT: "Expériences",
  FARE: "Tarifs",
  FIELD: "Champs",
  FLAG: "Feature flags",
  FOLDER: "Dossiers",
  FOLLOWER: "Abonnés",
  FORM: "Formulaires",
  FUNNEL: "Entonnoirs",
  GRADE: "Notes",
  GROUP: "Groupes",
  HASHTAG: "Hashtags",
  HOST: "Hôtes",
  INCIDENT: "Incidents",
  INDEX: "Index",
  INQUIRY: "Demandes",
  INSTANCE: "Instances",
  INSTRUCTOR: "Formateurs",
  INSTRUMENT: "Instruments financiers",
  INSURANCE: "Assurances",
  INTEGRATION: "Intégrations",
  INTERVIEW: "Entretiens",
  INVITATION: "Invitations",
  LAB: "Analyses médicales",
  LABEL: "Étiquettes",
  LEAVE: "Congés",
  LESSON: "Leçons",
  LIMIT: "Plafonds",
  LIST: "Listes",
  LISTING: "Annonces",
  LOAN: "Prêts",
  LOCATION: "Lieux",
  LOG: "Journaux",
  MACRO: "Macros",
  MANIFEST: "Manifestes",
  MATTER: "Dossiers juridiques",
  MEDIA: "Médias",
  MEMBER: "Membres",
  MENTION: "Mentions",
  MENU: "Menus",
  MERCHANT: "Commerçants",
  METRIC: "Métriques",
  MONITOR: "Sondes",
  MORTGAGE: "Crédits immobiliers",
  NEIGHBORHOOD: "Quartiers",
  NOTIFICATION: "Notifications",
  OBLIGATION: "Obligations",
  OFFER: "Offres",
  ORGANIZATION: "Organisations",
  ORGANIZER: "Organisateurs",
  PACKAGE: "Colis",
  PAGE: "Pages",
  PARCEL: "Colis",
  PARTICIPANT: "Participants",
  PARTY: "Parties",
  PATIENT: "Patients",
  PAYROLL: "Paies",
  PAYSLIP: "Bulletins de paie",
  PERMISSION: "Droits d'accès",
  PICKUP: "Enlèvements",
  POLICY: "Contrats d'assurance",
  POLL: "Sondages",
  POSITION: "Positions",
  POST: "Publications",
  PREMIUM: "Primes",
  PRESCRIPTION: "Ordonnances",
  PRODUCTION: "Productions",
  PROGRESS: "Progression",
  PROMOTION: "Promotions",
  PROVIDER: "Praticiens",
  QUERY: "Requêtes",
  QUEUE: "Files d'attente",
  QUIZ: "Quiz",
  QUOTA: "Quotas",
  RATE: "Tarifs",
  RATING: "Notes",
  RECEIPT: "Reçus",
  RECIPIENT: "Destinataires",
  RECORDING: "Enregistrements",
  REFERRAL: "Recommandations",
  REIMBURSEMENT: "Remboursements",
  REMINDER: "Rappels",
  REPLICA: "Répliques",
  REQUISITION: "Demandes de recrutement",
  RESEARCH: "Recherches",
  RESERVATION: "Réservations",
  RESOURCE: "Ressources",
  RESTAURANT: "Restaurants",
  RESUME: "CV",
  RIDE: "Courses",
  RIDER: "Passagers",
  RISK: "Risques",
  ROLE: "Rôles",
  ROUTE: "Itinéraires",
  RUN: "Exécutions",
  SCHEDULE: "Plannings",
  SCHEMA: "Schémas",
  SCORECARD: "Grilles d'évaluation",
  SEARCH: "Recherches",
  SEAT: "Places",
  SECRET: "Secrets",
  SEGMENT: "Segments",
  SENDER: "Expéditeurs",
  SERVICE: "Services",
  SESSION: "Sessions",
  SETTING: "Paramètres",
  SHARE: "Partages",
  SHIFT: "Créneaux de travail",
  SHOWING: "Visites",
  SIGNATURE: "Signatures",
  SLA: "SLA",
  SLO: "SLO",
  SLOT: "Créneaux",
  SPACE: "Espaces",
  STAFF: "Personnel",
  STAGE: "Étapes",
  STATEMENT: "Relevés",
  STUDENT: "Élèves",
  SURVEY: "Enquêtes",
  TABLE: "Tables",
  TAG: "Tags",
  TEMPLATE: "Modèles",
  TIMESHEET: "Feuilles de temps",
  TRACE: "Traces",
  TRACKING: "Suivis",
  TRANSCRIPT: "Transcriptions",
  TRANSFER: "Virements",
  TRASH: "Corbeille",
  TRIGGER: "Déclencheurs",
  TRIP: "Voyages",
  VALUATION: "Estimations",
  VEHICLE: "Véhicules",
  VENUE: "Lieux",
  VERSION: "Versions",
  VOLUME: "Volumes",
  VULNERABILITY: "Vulnérabilités",
  WAITLIST: "Listes d'attente",
  WAREHOUSE: "Entrepôts",
  WATCHLIST: "Listes de suivi",
  WEBHOOK: "Webhooks",
  WEBINAR: "Webinaires",
  WIDGET: "Widgets",
  WORKFLOW: "Workflows",
  WORKSPACE: "Espaces de travail",
};

export const objectFr = (key: string) => OBJECT_FR[key] ?? key.charAt(0) + key.slice(1).toLowerCase();
export const verbFr = (key: string) => VERB_FR[key] ?? key;

/** « CREATE_DEAL » → « Créer · Opportunités » */
export function capabilityFr(key: string) {
  if (key === "UNMAPPED") return "Non classé";
  const i = key.lastIndexOf("_");
  return `${verbFr(key.slice(0, i))} · ${objectFr(key.slice(i + 1))}`;
}

export const CHANNEL_INFO: Record<string, { name: string; short: string; help: string; agent: boolean }> = {
  MCP: {
    name: "Serveur MCP",
    short: "MCP",
    help: "Point d'accès standard qui permet à n'importe quel agent IA de lire et d'agir dans l'outil.",
    agent: true,
  },
  CONNECTOR_CLAUDE: {
    name: "Connecteur Claude",
    short: "Claude",
    help: "L'outil s'installe en un clic dans Claude, qui peut alors agir dedans.",
    agent: true,
  },
  APP_CHATGPT: {
    name: "App ChatGPT",
    short: "ChatGPT",
    help: "L'outil est disponible comme app dans ChatGPT.",
    agent: true,
  },
  AUTOMATION: {
    name: "Zapier",
    short: "Zapier",
    help: "Accès indirect par des automatisations Zapier. Utile, mais moins direct qu'un canal agent.",
    agent: true,
  },
  AGENT_CARD: {
    name: "Carte d'agent",
    short: "Carte",
    help: "Fiche technique standard (A2A) qui présente l'outil à d'autres agents.",
    agent: true,
  },
  COMMERCE_PROTOCOL: { name: "Commerce agentique", short: "Commerce", help: "Paiement ou commande par un agent.", agent: true },
  API: {
    name: "API",
    short: "API",
    help: "Accès pour développeurs : un agent ne peut l'utiliser que si quelqu'un a écrit une intégration.",
    agent: false,
  },
  SDK: { name: "Kit développeur", short: "SDK", help: "Bibliothèque de code pour les développeurs.", agent: false },
  LLMS_TXT: { name: "Fichier llms.txt", short: "llms.txt", help: "Fichier qui guide les IA sur le site de l'éditeur.", agent: false },
  OPENAPI: { name: "API documentée", short: "OpenAPI", help: "Documentation d'API publique, lisible par les machines.", agent: false },
};
export const channelName = (t: string) => CHANNEL_INFO[t]?.name ?? t;

export const LEVEL_INFO: Record<string, { name: string; help: string }> = {
  OBSERVED: { name: "Vérifié", help: "Constaté directement : annuaire officiel, liste d'outils du serveur, spec d'API." },
  DECLARED: { name: "Annoncé", help: "Affirmé par l'éditeur dans sa documentation, pas encore vérifié directement." },
  ESTIMATED: { name: "Estimé", help: "Déduit ou estimé, à confirmer." },
};
export const levelName = (l: string) => LEVEL_INFO[l]?.name ?? l;

export const READINESS_FR: Record<string, string> = { High: "Avancé", Medium: "Intermédiaire", Low: "En retard" };

export const COMPONENT_INFO: Record<string, { name: string; help: string }> = {
  distribution: { name: "Présence", help: "Est-il accessible aux agents par des canaux officiels (serveur MCP, Claude, ChatGPT…) ?" },
  coverage: { name: "Étendue", help: "Part des actions possibles dans ce marché qu'un agent peut faire chez lui." },
  depth: { name: "Actions concrètes", help: "Part des actions qui modifient des données (créer, modifier…) et pas seulement de lecture." },
  structured: { name: "Lisibilité", help: "Est-il facile à comprendre pour une IA (llms.txt, API documentée, carte d'agent) ?" },
  transaction: { name: "Paiement", help: "Un agent peut-il commander ou payer ?" },
  freshness: { name: "Nouveautés", help: "A-t-il lancé ou mis à jour un canal agent ces 90 derniers jours ?" },
};

export const PROVIDER_FR: Record<string, string> = { chatgpt: "ChatGPT", gemini: "Gemini", claude: "Claude", perplexity: "Perplexity" };
